AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 29
    MemorySize: 128

Resources:
  towApifunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - server.ts
        External:
          - "@aws-sdk/*"
        Format: esm
      BuildEnvironment:
        NodeVersion: 18
        PackageManager: yarn # Explicitly tell SAM to use yarn
        Variables:
          NODE_ENV: production
    Properties:
      Handler: server.handler
      Runtime: nodejs18.x
      CodeUri: ./apps/towmycar_api
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /tow_api
            Method: any
