import { DocumentMetadataEnum } from "@aws-sdk/client-ssm";

export enum UserGroup {
  USER = "user",
  ADMIN = "admin",
  DRIVER = "driver",
}

export enum NotificationType {
  DRIVER_REGISTERED = "DRIVER_REGISTERED",
  USER_REQUEST = "USER_REQUEST",
  USER_CREATED = "USER_CREATED",
  USER_ACCEPTED = "USER_ACCEPTED",
  DRIVER_REJECTED = "DRIVER_REJECTED",
  DRIVER_CLOSED = "DRIVER_CLOSED",
  DRIVER_QUOTATION_UPDATED = "DRIVER_QUOTATION_UPDATED",
  DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
  DRIVER_QUOTED = "DRIVER_QUOTED",
  DRIVER_ACCEPTED = "DRIVER_ACCEPTED",
  DRIVER_NOTIFICATION = "DRIVER_NOTIFICATION",
  USER_NOTIFICATION = "USER_NOTIFICATION",
  USER_REJECTED = "USER_REJECTED",
  RATING_REVIEW = "RATING_REVIEW",
  DRIVER_CHAT_INITIATED = "DRIVER_CHAT_INITIATED",
  USER_CHAT_INITIATED = "USER_CHAT_INITIATED",
}

export enum DriverStatus {
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  QUOTED = "QUOTED",
  PENDING = "PENDING",
  CLOSED = "CLOSED",
}

export enum UserStatus {
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
  INPROGRESS = "INPROGRESS",
  CLOSED = "CLOSED",
}

export enum DeliveryNotificationType {
  EMAIL = "EMAIL",
  SMS = "SMS",
  PUSH = "PUSH",
}

export enum BreakdownRequestStatus {
  INPROGRESS = "INPROGRESS",
  WAITING = "WAITING",
  CLOSED = "CLOSED",
  QUOTED = "QUOTED",
}
export enum SmsNotificationType {
  DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
  REQUEST_STATUS_UPDATE = "REQUEST_STATUS_UPDATE",
  PAYMENT_CONFIRMATION = "PAYMENT_CONFIRMATION",
}

export enum MessageSender {
  Driver = "driver",
  Customer = "customer",
}
