import { DocumentMetadataEnum } from "@aws-sdk/client-ssm";

export enum UserGroup {
  USER = "user",
  ADMIN = "admin",
  DRIVER = "driver",
}

export enum NotificationType {
  DRIVER_REGISTERED = "DRIVER_REGISTERED",
  USER_REQUEST = "USER_REQUEST",
  USER_CREATED = "USER_CREATED",
  USER_ACCEPT = "USER_ACCEPT",
  DRIVER_REJECT = "DRIVER_REJECT",
  DRIVER_CLOSED = "DRIVER_CLOSED",
  DRIVER_QUOTATION_UPDATED = "DRIVER_QUOTATION_UPDATED",
  DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
  DRIVER_QUOTED = "DRIVER_QUOTE",
  DRIVER_ACCEPT = "DRIVER_ACCEPT",
  DRIVER_NOTIFICATION = "DRIVER_NOTIFICATION",
  USER_NOTIFICATION = "USER_NOTIFICATION",
  USER_REJECT = "USER_REJECT",
  RATING_REVIEW = "RATING_REVIEW",
}

export enum DriverStatus {
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  QUOTED = "QUOTED",
  PENDING = "PENDING",
  CLOSED = "CLOSED",
}

export enum UserStatus {
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
  INPROGRESS = "INPROGRESS",
}

export enum BaseNotificationType {
  EMAIL = "EMAIL",
  SMS = "SMS",
  PUSH = "PUSH",
}

export enum BreakdownRequestStatus {
  INPROGRESS = "INPROGRESS",
  WAITING = "WAITING",
  CLOSED = "CLOSED",
  QUOTED = "QUOTED",
}
export enum SmsNotificationType {
  DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
  REQUEST_STATUS_UPDATE = "REQUEST_STATUS_UPDATE",
  PAYMENT_CONFIRMATION = "PAYMENT_CONFIRMATION",
}
