import { DocumentMetadataEnum } from "@aws-sdk/client-ssm";

export enum UserGroup {
  USER = "user",
  ADMIN = "admin",
  DRIVER = "driver",
}

export enum NotificationType {
  DRIVER_REGISTERED = "DRIVER_REGISTERED",
  USER_REQUEST = "USER_REQUEST",
  USER_CREATED = "USER_CREATED",
  USER_ACCEPTED = "USER_ACCEPTED",
  DRIVER_REJECTED = "DRIVER_REJECTED",
  DRIVER_CLOSED = "DRIVER_CLOSED",
  DRIVER_QUOTATION_UPDATED = "DRIVER_QUOTATION_UPDATED",
  DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
  DRIVER_QUOTED = "DRIVER_QUOTED",
  DRIVER_ACCEPTED = "DRIVER_ACCEPTED",
  DRIVER_NOTIFICATION = "DRIVER_NOTIFICATION",
  USER_NOTIFICATION = "USER_NOTIFICATION",
  USER_REJECTED = "USER_REJECTED",
  RATING_REVIEW = "RATING_REVIEW",
  DRIVER_CHAT_INITIATED = "DRIVER_CHAT_INITIATED",
  USER_CHAT_INITIATED = "USER_CHAT_INITIATED",
  ADMIN_APPROVAL_REQUEST = "ADMIN_APPROVAL_REQUEST",
}

export enum DriverStatus {
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  QUOTED = "QUOTED",
  PENDING = "PENDING",
  CLOSED = "CLOSED",
}

export enum NotificationStatus {
  PENDING = "PENDING",
  SENT = "SENT",
  FAILED = "FAILED",
}

export enum UserStatus {
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  PENDING = "PENDING",
  INPROGRESS = "INPROGRESS",
  CLOSED = "CLOSED",
}

export enum DeliveryNotificationType {
  EMAIL = "EMAIL",
  SMS = "SMS",
  PUSH = "PUSH",
}

export enum BreakdownRequestStatus {
  INPROGRESS = "INPROGRESS",
  WAITING = "WAITING",
  CLOSED = "CLOSED",
  QUOTED = "QUOTED",
}

export enum DriverApprovalStatus {
  INITIAL = "INITIAL",
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
}

export enum DriverAvailabilityStatus {
  AVAILABLE = "AVAILABLE",
  UNAVAILABLE = "UNAVAILABLE",
}

export enum DocumentApprovalStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  UPLOADED = "UPLOADED",
}

export enum DeliveryTimeframe {
  ASAP = "ASAP",
  WITHIN_DAY = "WITHIN_DAY",
  WITHIN_WEEK = "WITHIN_WEEK",
  WITHIN_MONTH = "WITHIN_MONTH",
}

export enum UploadDocumentType {
  DRIVER_LICENSE_FRONT = "DRIVER_LICENSE_FRONT",
  DRIVER_LICENSE_BACK = "DRIVER_LICENSE_BACK",
  VEHICLE_REGISTRATION = "VEHICLE_REGISTRATION",
  VEHICLE_INSURANCE = "VEHICLE_INSURANCE",
  VEHICLE_PHOTO = "VEHICLE_PHOTO",
  PUBLIC_LIABILITY_INSURANCE = "PUBLIC_LIABILITY_INSURANCE",
}

export enum SmsNotificationType {
  DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
  REQUEST_STATUS_UPDATE = "REQUEST_STATUS_UPDATE",
  PAYMENT_CONFIRMATION = "PAYMENT_CONFIRMATION",
}

export enum MessageSender {
  Driver = "driver",
  Customer = "customer",
}
