export enum SmsNotificationType {
  DRIVER_ASSIGNED = 'DRIVER_ASSIGNED',
  REQUEST_STATUS_UPDATE = 'REQUEST_STATUS_UPDATE',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
  NOTIFY_DRIVER = 'NOTIFY_DRIVER'
}